### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by Grrman**

### CODE REVIEW

**Comment by gmangavin** [comment]
You need to get cheesecake

**Comment by Charlie92** [comment]
Gavin we're making a website not cheesecake

**Comment by Grrman** [comment]
Nobody likes cheesecake

**Comment by LoganGP** [comment]
I like it.

**Comment by Grrman** [comment]
no you dont

**Comment by LoganGP** [comment]
YEAH

**Comment by Grrman** [comment]
sike

**Comment by Charlie92** [comment]
Why do you have a picture of entriean?

**Comment by LoganGP** [comment]
Stop being rude. Thats why you're not owner.

**Comment by Grrman** [comment]
Stop being a Logan. That's rude ya know?

**Comment by Charlie92** [comment]
I can hear what you're saying Logan

**Comment by Charlie92** [comment]
Races

**Comment by Grrman** [comment]
charlies im black help

**Comment by Charlie92** [comment]
Okay?

**Pull request merged**
